sudo: false
language: python
python:
- 2.7
os:
- linux
install:
- pip install --upgrade cwltool
- pip install --upgrade cwltest
script: bash run_test.sh
branches:
  only:
  - v1.0.2
notifications:
  email: false
